{{- $fullName := include "source-telegram.fullname" . }}
{{- $portGrpc := .Values.service.portGrpc }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "source-telegram.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ $portGrpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "source-telegram.selectorLabels" . | nindent 4 }}
