apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "source-telegram.fullname" . }}
  labels:
    {{- include "source-telegram.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "source-telegram.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "source-telegram.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "source-telegram.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: API_TELEGRAM_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ include "source-telegram.fullname" . }}-tokens"
                  key: id
            - name: API_TELEGRAM_HASH
              valueFrom:
                secretKeyRef:
                  name: "{{ include "source-telegram.fullname" . }}-tokens"
                  key: hash
            - name: API_TELEGRAM_PHONE
              valueFrom:
                secretKeyRef:
                  name: "{{ include "source-telegram.fullname" . }}-tokens"
                  key: phone
            - name: API_TELEGRAM_FEED_CHAT_IDS
              value: "{{ join "," .Values.api.telegram.feed.chatIds }}"
            - name: API_WRITER_URI
              value: "{{ .Values.api.writer.uri }}"
            - name: LOG_LEVEL
              value: "{{ .Values.log.level }}"
            - name: REPLICA_RANGE
              value: "{{ .Values.replicaCount }}"
            - name: REPLICA_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          stdin: true
          tty: true
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - ls
          readinessProbe:
            exec:
              command:
                - ls
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
