apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "producer-telegram.fullname" . }}
  labels:
    {{- include "producer-telegram.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "producer-telegram.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "producer-telegram.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "producer-telegram.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: API_TELEGRAM_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ include "producer-telegram.fullname" . }}-tokens"
                  key: id
            - name: API_TELEGRAM_HASH
              valueFrom:
                secretKeyRef:
                  name: "{{ include "producer-telegram.fullname" . }}-tokens"
                  key: hash
            - name: API_TELEGRAM_FEED_CHAT_IDS
              value: "{{ .Values.api.telegram.feed.chatIds }}"
            - name: API_WRITER_URI
              value: "{{ .Values.api.writer.uri }}"
            - name: LOG_LEVEL
              value: "{{ .Values.log.level }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: server-cert
              mountPath: "/etc/server-cert"
              readOnly: true
      volumes:
        - name: server-cert
          secret:
            secretName: secret-producer-telegram-tls-server
            items:
              - key: tls.crt
                path: tls.crt
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
